name: Build and Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main   # <- 如果你的默认分支不是 main，改成你的分支名
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo cache dir (avoid /tmp permission issues)
        run: |
          export HUGO_CACHE_DIR="${GITHUB_WORKSPACE}/.hugo_cache"
          mkdir -p "$HUGO_CACHE_DIR"
          # ensure runner user owns it
          sudo chown -R "$(whoami):$(whoami)" "$HUGO_CACHE_DIR"
          echo "HUGO_CACHE_DIR=$HUGO_CACHE_DIR" >> $GITHUB_ENV

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.0'  # 按需修改

      - name: Hugo modules: clean & get
        env:
          HUGO_CACHE_DIR: ${{ env.HUGO_CACHE_DIR }}
        run: |
          hugo mod clean || true
          hugo mod get
          hugo mod tidy

      - name: Build site
        env:
          HUGO_CACHE_DIR: ${{ env.HUGO_CACHE_DIR }}
        run: |
          hugo --minify -v

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
