name: Build and Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # 从一开始就让所有步骤看到这些 env，避免任何时序问题
    env:
      HUGO_CACHE_DIR: ${{ github.workspace }}/.hugo_cache
      GOPATH: ${{ github.workspace }}/.gopath
      GOMODCACHE: ${{ github.workspace }}/.gopath/pkg/mod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove old /tmp hugo cache (if exists) and ensure workspace cache dirs
        run: |
          echo "Checking for old /tmp/hugo_cache_runner and removing if present (safe cleanup)..."
          if [ -d /tmp/hugo_cache_runner ]; then
            echo "/tmp/hugo_cache_runner exists. Removing it to avoid permission conflicts."
            sudo rm -rf /tmp/hugo_cache_runner || true
          else
            echo "/tmp/hugo_cache_runner not present."
          fi

          echo "Creating workspace cache dirs and ensuring runner owns them..."
          mkdir -p "${HUGO_CACHE_DIR}" "${GOMODCACHE}"
          sudo chown -R "$(whoami):$(whoami)" "${HUGO_CACHE_DIR}" "${GOMODCACHE}"
          echo "After setup, directory listing:"
          ls -ld "${HUGO_CACHE_DIR}" "${GOMODCACHE}" /tmp || true

      - name: Setup Hugo (install)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.0'

      - name: 'Hugo modules: clean & get (use workspace caches)'
        run: |
          # ensure go uses our GOPATH/GOMODCACHE (env already set at job level)
          export GOPATH="${GOPATH}"
          export GOMODCACHE="${GOMODCACHE}"
          echo "Using GOPATH=${GOPATH}"
          echo "Using GOMODCACHE=${GOMODCACHE}"
          hugo mod clean || true
          hugo mod get
          hugo mod tidy

      - name: Build site
        run: |
          hugo --minify -v
          echo "Build finished. public/ contents:"
          ls -la ./public || true

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
