name: Build and Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # ---- 关键：把这些 env 放在 job 级别，确保从第一步开始生效 ----
    env:
      HUGO_CACHE_DIR: ${{ github.workspace }}/.hugo_cache
      GOPATH: ${{ github.workspace }}/.gopath
      GOMODCACHE: ${{ github.workspace }}/.gopath/pkg/mod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure workspace cache dirs exist and are owned by runner
        # This step creates the directories and chowns them so subsequent steps can write
        run: |
          echo "Making sure caches exist and are writable..."
          mkdir -p "${HUGO_CACHE_DIR}" "${GOMODCACHE}"
          sudo chown -R "$(whoami):$(whoami)" "${HUGO_CACHE_DIR}" "${GOMODCACHE}"
          ls -ld "${HUGO_CACHE_DIR}" "${GOMODCACHE}"

      - name: Setup Hugo (install)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.0'

      - name: 'Hugo modules: clean & get (use workspace caches)'
        run: |
          # ensure go uses our GOPATH/GOMODCACHE (env already set at job level)
          export GOPATH="${GOPATH}"
          export GOMODCACHE="${GOMODCACHE}"
          hugo mod clean || true
          hugo mod get
          hugo mod tidy

      - name: Build site
        run: |
          hugo --minify -v
          echo "Build finished. public/ contents:"
          ls -la ./public || true

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
